# Generated by Django 5.0.6 on 2024-05-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogging", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="category",
            field=models.CharField(
                choices=[
                    ("world", "World"),
                    ("environment", "Environment"),
                    ("technology", "Technology"),
                    ("design", "Design"),
                    ("culture", "Culture"),
                    ("business", "Business"),
                    ("politics", "Politics"),
                    ("opinion", "Opinion"),
                    ("science", "Science"),
                    ("health", "Health"),
                    ("style", "Style"),
                    ("travel", "Travel"),
                ],
                default="world",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
