# Generated by Django 5.0.6 on 2024-05-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogging", "0002_alter_blogpost_category_alter_blogpost_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
